### ISSUE TITLE
Unable to fetch head metadata on search strategy when search keys has more than one word

### ISSUE THREAD

**Issue by nicholasio** [10up/headstartwp#537] opened 2023-06-30 13:06 UTC
### Describe the bug

There seem to be a few issues with the Yoast get_head endpoint that is not properly recognizing the requested page as a search page.

### Steps to Reproduce

1. Go To Search
2. Search for two words
3. Missing/wrong metatags or crash.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lucymtc** [comment] 2023-07-04 10:23
@nicholasio I have also noticed an issue with get_head endpoint when appending the url param with 
'`${getWPUrl()}/?s=${params.search}` 
If the WP url returned by getWPUrl() has a trailing slash, this will add double slash to `//?s=` where get_head endpoint returns page not found. 
I needed to do `const wpUrl = getWPUrl().replace(/\/$/, '');` first to remove the trailing slash

**Comment by nicholasio** [comment] 2023-07-05 01:38
Thanks @lucymtc Here are a few things I found:

- Yoast is not properly detecting a search page via the `get_head` function.
- Searching for multiple words crashes the `get_head` query and thus makes the framework default to the metadata of the first post returned.
- Yoast also does not yoast_head to the WordPress search endpoint.

I'm not sure if we can rely on on Yoast to generate the meta tags for the search page.

**Comment by nicholasio** [comment] 2023-12-19 14:54
Alternative solution: Have the SearchStrategy manually build the yoast_seo object and yoast_html fields manually with basica meta tags.

**Comment by lucymtc** [comment] 2024-01-09 05:17
@nicholasio for the issue:

- Searching for multiple words crashes the get_head query and thus makes the framework default to the metadata of the first post returned.

I found what the problem is and opened an [Issue](https://github.com/Yoast/wordpress-seo/issues/21019) and [PR](https://github.com/Yoast/wordpress-seo/pull/21020) in Yoast

I tried to override the validate callback for the URL, the way to do this would be to register a get_head endpoint from our side as if `$override` is set to false in `register_rest_route` WP merges with newer overriding if duplicate keys exist. 
The problem is that you need to pass in the exact arguments that the original `register_rest_route` (the one in Yoast) is called with, and the callback function depends on an instance of` \Yoast\WP\SEO\Routes\Indexables_Head_Route` which has dependencies in other Yoast classes and doesn't make it straight forward to instantiate the class. Unless Yoast exposes an instance of the class but I haven't found anything so far. 
I tested other hooks to try override the validation callback without success.

**Comment by lucymtc** [comment] 2024-01-16 12:55
Update on fix for _"Searching for multiple words crashes the get_head query and thus makes the framework default to the metadata of the first post returned."_ has been merged into Yoast via this PR https://github.com/Yoast/wordpress-seo/pull/21032

**Comment by lucymtc** [comment] 2024-01-19 11:37
Opened PR https://github.com/10up/headstartwp/pull/663 for:
Yoast is not properly detecting a search page via the get_head function.
Yoast does not yoast_head to the WordPress search endpoint.

**Comment by nicholasio** [comment] 2024-01-26 14:01
> Update on fix for _"Searching for multiple words crashes the get_head query and thus makes the framework default to the metadata of the first post returned."_ has been merged into Yoast via this PR [Yoast/wordpress-seo#21032](https://github.com/Yoast/wordpress-seo/pull/21032)

Looks like the PR merged will be released in Yoast 22.0.

**Closed as completed** 2024-01-26 14:00 UTC
